#pragma once

#include "camera_params.h"
#include "lights_params.h"
#include "materials_params.h"
#include "objects/curve_params.h"
#include "objects/group_params.h"
#include "objects/mesh_params.h"
#include "objects/object_type.h"
#include "objects/object_params_pointer.h"
#include "objects/plane_params.h"
#include "objects/revsurface_params.h"
#include "objects/sphere_params.h"
#include "objects/transform_params.h"
#include "objects/triangle_params.h"
