#pragma once

#include "camera_params.h"
#include "lights_params.h"
#include "materials_params.h"
#include "spaces/curve_params.h"
#include "spaces/group_params.h"
#include "spaces/mesh_params.h"
#include "spaces/object_type.h"
#include "spaces/object_params_pointer.h"
#include "spaces/plane_params.h"
#include "spaces/revsurface_params.h"
#include "spaces/sphere_params.h"
#include "spaces/transform_params.h"
#include "spaces/triangle_params.h"
